com.swiftly.gateway.GatewayApplication=

# Stork/Eureka setup
quarkus.stork.service-discovery-eureka.server-url=http://eureka:8761/eureka
# Rest client base URLs will be resolved via Stork
quarkus.rest-client."com.swiftly.gateway.infrastructure.client.DownstreamHealthClient".url=stork://<service-name>
health.check.timeout=5S